name: cards
recipe: lamp
config:
  php: '8.3'
  webroot: public_html
  database: mysql:8.0
  composer_version: '2'
  xdebug: false

proxy:
  appserver:
    - cards.lndo.site

tooling:
  composer:
    service: appserver
